language: java
sudo: false # faster builds
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
services:
  -postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database db_springboot;' -U postgres
  -cp config/database.yml.travis config/database.yml
